ALTER TABLE "categories" ADD COLUMN IF NOT EXISTS "emoji" text DEFAULT '🏷️' NOT NULL;
--> statement-breakpoint
UPDATE "categories"
SET "emoji" = CASE lower("name")
  WHEN 'housing' THEN '🏠'
  WHEN 'utilities' THEN '💡'
  WHEN 'food & dining' THEN '🍽️'
  WHEN 'transportation' THEN '🚗'
  WHEN 'healthcare' THEN '🏥'
  WHEN 'shopping' THEN '🛍️'
  WHEN 'entertainment' THEN '🎬'
  WHEN 'travel' THEN '✈️'
  WHEN 'education' THEN '🎓'
  WHEN 'financial' THEN '🏦'
  WHEN 'personal care' THEN '💆'
  WHEN 'family & pets' THEN '👪'
  WHEN 'insurance' THEN '🛡️'
  WHEN 'business & work' THEN '💼'
  WHEN 'salary & employment' THEN '💵'
  WHEN 'freelance & contract work' THEN '🧑‍💻'
  WHEN 'business income' THEN '🏪'
  WHEN 'gig economy' THEN '🚲'
  WHEN 'online sales' THEN '🛒'
  WHEN 'rental income' THEN '🏘️'
  WHEN 'investment income' THEN '📈'
  WHEN 'cryptocurrency' THEN '🪙'
  WHEN 'royalties & licensing' THEN '🎼'
  WHEN 'content creator income' THEN '🎥'
  WHEN 'bank rewards & cashback' THEN '💳'
  WHEN 'refunds & reimbursements' THEN '🔁'
  WHEN 'government benefits' THEN '🏛️'
  WHEN 'insurance payouts' THEN '🛡️'
  WHEN 'education & grants' THEN '🎓'
  WHEN 'gifts & family support' THEN '🎁'
  WHEN 'transfers received' THEN '🔄'
  WHEN 'agriculture & farming' THEN '🚜'
  WHEN 'prizes & winnings' THEN '🏆'
  WHEN 'asset sales' THEN '🏷️'
  WHEN 'legal & settlements' THEN '⚖️'
  WHEN 'foreign income' THEN '🌍'
  WHEN 'miscellaneous income' THEN '💰'
  WHEN 'emergency fund' THEN '🚨'
  WHEN 'general savings' THEN '🐷'
  WHEN 'retirement savings' THEN '🌅'
  WHEN 'investment savings' THEN '📊'
  WHEN 'education savings' THEN '🎓'
  WHEN 'home savings' THEN '🏡'
  WHEN 'vehicle savings' THEN '🚙'
  WHEN 'travel savings' THEN '🧳'
  WHEN 'healthcare savings' THEN '🩺'
  WHEN 'wedding savings' THEN '💍'
  WHEN 'baby & family savings' THEN '🍼'
  WHEN 'business savings' THEN '🏢'
  WHEN 'technology savings' THEN '💻'
  WHEN 'gift savings' THEN '🎁'
  WHEN 'tax savings' THEN '🧾'
  WHEN 'insurance reserve' THEN '🛡️'
  WHEN 'debt payoff fund' THEN '✅'
  WHEN 'large purchase fund' THEN '🛋️'
  WHEN 'pet savings' THEN '🐾'
  WHEN 'charity savings' THEN '🤝'
  WHEN 'crypto savings' THEN '🪙'
  WHEN 'gold & precious metals' THEN '🥇'
  WHEN 'foreign currency savings' THEN '💱'
  WHEN 'children''s future' THEN '🧒'
  WHEN 'other goal-based savings' THEN '🎯'
  ELSE CASE "kind"
    WHEN 'expense' THEN '💳'
    WHEN 'income' THEN '💵'
    WHEN 'savings' THEN '🐷'
    ELSE '🏷️'
  END
END
WHERE "emoji" = '🏷️';